spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/car?characterEncoding=utf-8&useSSL=false
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: /META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.upload-path}
  jackon:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.pojo

server:
  servlet:
    context-path: /car
  port: 8083

web:
  upload-path: E:\car-code\img\
file:
  uploadFolder: d://weixinuploadFiles/